### ISSUE TITLE
My Advice

### ISSUE THREAD

**Issue by lmboom** [paraparadox/cars-pet-project#1]
If we are talking about WebApps My advice is 
[This](https://www.kobo.com/us/en/ebook/let-s-go-learn-to-build-professional-web-applications-with-go)

Проблем по коду особых нет кроме как определений сущностей и оверлоада главной функции
Но в больших проектах так писать не получится

**Comment by roadiedev** [comment]
Yooohooo!
Классно, спасибо большое бро.
Про определение сущностей в этой книге тоже есть, да?

**Comment by roadiedev** [comment]
Hello once again :)

I've read the book. It is awesome! Thank you very much for advice brother @lmboom ! It was really informative and useful!
Closing this issue.

P.S: here is the link to the repository with project from that book: https://github.com/paraparadox/snippetbox
